### ISSUE TITLE
Support for new beta Dev Mode?

### ISSUE THREAD

**Issue by jmatsushita** [kat-tax/figma-to-react-native#12]
Hi there,

I'm new to the figma plugin ecosystem, but was looking for a react-native integration, and was glad to find your project! I'm wondering if you're considering adding support for the Dev mode that Figma recently released in Beta? 

<img width="826" alt="image" src="https://github.com/kat-tax/figma-to-react-native/assets/356097/94cd643d-23f9-44b6-82a0-e91244a5e065">

Cheers,

Jun

**Comment by csnvrl** [comment]
+1

**Comment by TheUltDev** [comment]
I released dev mode support yesterday shortly after it was announced. I will push the code changes today.

This included codegen in the Inspect panel and the Plugin tab in dev mode.

There are other features planned such as an option to export only components marked "Ready for Dev", improved AutoLayout, and variables support.

**Comment by jmatsushita** [comment]
That's awesome 🎉
