### ISSUE TITLE
Status of Tamagui support 

### ISSUE THREAD

**Issue by jmatsushita** [kat-tax/figma-to-react-native#13]
Hi again,

I see in this PR https://github.com/kat-tax/figma-to-react-native/pull/7 that some work was done towards supporting Tamagui. That is the component library I'm using currently and I'd love to know if this is part of your roadmap for the plugin, and also offer some help to test features if that would be useful.

Cheers,

Jun

**Comment by jmatsushita** [comment]
Hey @TheUltDev I looked a bit at the code and wonder if I got the following more or less right :) 



I think building up support for Tamagui in `figma-to-react-native` would entail: 
- [ ] Seems that the `modules/fig` parsing layer is currently fairly coupled with a bare react-native approach (stylesheet, flex layout), so in the future probably this layer should be `flavor` indepedent, but to get started it might make more sense to have a `modules/fig-tamagui` module to try and workout concretely what could be needed? It looks like [the types could remain the same](https://github.com/kat-tax/figma-to-react-native/blob/f412fffe2040c5ce71d8be674cead2b1dcb0c7ae/src/types/parse.ts#L21-L22) but the `parseNode` and `parseStyle` functions for tamagui would endup generating `props` instead of `styles` ?
- [ ] Creating `generateBundle` and `generateTheme` functions for `tamagui` https://github.com/kat-tax/figma-to-react-native/blob/f412fffe2040c5ce71d8be674cead2b1dcb0c7ae/src/modules/gen/index.ts#L7
 - [ ] Write the Figma component translation layer in `utils` specifically.
   - [ ] Management  of `XStack` and `YStack` tamagui primitives. Maybe the `node.layout` properties of figma should not just map to a `flexDirection`? Not sure if we can call `layout()` from `generateComponent` to choose the Stack?
   - [ ] Not sure if [the root ](https://github.com/kat-tax/figma-to-react-native/blob/master/src/modules/gen/react-native/bundle.ts#L36) should be a `Stack` or if we should choose a `XStack` or `YStack` depending on figma component layout.
- [ ] At first ignoring `parseData.stylesheet` might make sense, targeting `tamagui` (rather than `@tamagui/core` at first), and then we could generate a `tamagui.config.ts` file (alongside `themes`,`tokens`...)

![image](https://github.com/kat-tax/figma-to-react-native/assets/356097/e8038f34-c72a-4402-9e2c-c203c1210541) 

I wonder if @natew would be interested in joining the conversation :) I worry that this is somewhat competing (in a "gentle open source alternatives" kind of way hopefully :) ) with the Tamagui Studio product... Or maybe this is an opportunity to build on a common core?

**Comment by TheUltDev** [comment]
@jmatsushita You're correct in your parsing of the code.

I will be rewriting `modules/fig` to use the new codegen functions as well as decouple from stylesheets. I will build a flavor agnostic intermediate representation to be used for both stylesheets and tamagui. 

As far as Tamagui Studio goes, I'm actually going to be working on that. Though my focus is currently on rewriting this plugin. This plugin won't really compete with it as they are focused on two different directions and functions. Studio allows you to update your theme and sync it to Figma.

**Comment by jmatsushita** [comment]
That's all great to hear, I'm excited about the possibilities!

**Comment by TheUltDev** [comment]
The rewrite is done. Tamagui support isn't currently the priority, but PRs are welcome.

I will get to Tamagui after the core of the plugin is stable.
